version: "2"
run:
  concurrency: 4
  go: "1.24"
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unconvert
    - unused
    - misspell
  settings:
    errcheck:
      exclude-functions:
        - fmt.*
        - io.Close
    govet:
      settings:
        printf:
          funcs:
            - github.com/superfly/flyctl/terminal.Debugf
            - github.com/superfly/flyctl/terminal.Infof
            - github.com/superfly/flyctl/terminal.Warnf
            - github.com/superfly/flyctl/terminal.Errorf
            - github.com/superfly/flyctl/render.Printf
            - github.com/superfly/flyctl/render.Detailf
            - github.com/superfly/flyctl/render.Donef
    staticcheck:
      checks:
        - all
        - -SA1019 # ... is deprecated
        - -ST1003 # struct field ... should be ... (mostly acronyms such as Http -> HTTP)
        - -ST1005 # error strings should not be capitalized
        - -ST1008 # error should be returned as the last argument
        - -ST1012 # error var ... should have name of the form Err...
        - -QF1001 # could apply De Morgan's law
        - -QF1002 # could use tagged switch
        - -QF1003 # could use tagged switch on app
        - -QF1008 # could remove embedded field ... from selector
        - -QF1012 # Use fmt.Fprintf(...) instead of WriteString(fmt.Sprintf(...))
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        source: "^//go:generate "
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
