// Code generated by "stringer -type=flapsAction"; DO NOT EDIT.

package flaps

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[appCreate-0]
	_ = x[machineLaunch-1]
	_ = x[machineUpdate-2]
	_ = x[machineStart-3]
	_ = x[machineWait-4]
	_ = x[machineStop-5]
	_ = x[machineRestart-6]
	_ = x[machineGet-7]
	_ = x[machineList-8]
	_ = x[machineDestroy-9]
	_ = x[machineKill-10]
	_ = x[machineFindLease-11]
	_ = x[machineAcquireLease-12]
	_ = x[machineRefreshLease-13]
	_ = x[machineReleaseLease-14]
	_ = x[machineExec-15]
	_ = x[machinePs-16]
	_ = x[machineCordon-17]
	_ = x[machineUncordon-18]
	_ = x[volumeList-19]
	_ = x[volumeCreate-20]
	_ = x[volumetUpdate-21]
	_ = x[volumeGet-22]
	_ = x[volumeSnapshotCreate-23]
	_ = x[volumeSnapshotList-24]
	_ = x[volumeExtend-25]
	_ = x[volumeDelete-26]
}

const _flapsAction_name = "appCreatemachineLaunchmachineUpdatemachineStartmachineWaitmachineStopmachineRestartmachineGetmachineListmachineDestroymachineKillmachineFindLeasemachineAcquireLeasemachineRefreshLeasemachineReleaseLeasemachineExecmachinePsmachineCordonmachineUncordonvolumeListvolumeCreatevolumetUpdatevolumeGetvolumeSnapshotCreatevolumeSnapshotListvolumeExtendvolumeDelete"

var _flapsAction_index = [...]uint16{0, 9, 22, 35, 47, 58, 69, 83, 93, 104, 118, 129, 145, 164, 183, 202, 213, 222, 235, 250, 260, 272, 285, 294, 314, 332, 344, 356}

func (i flapsAction) String() string {
	if i < 0 || i >= flapsAction(len(_flapsAction_index)-1) {
		return "flapsAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _flapsAction_name[_flapsAction_index[i]:_flapsAction_index[i+1]]
}
