#!/usr/bin/with-contenv bash

# Switch to web user
su webuser

#Bring up PHP FPM
exec /usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --server=swoole --host=0.0.0.0 --rpc-port=6001 --port=8000
