name: Build
on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  preflight:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/preflight.yml
    secrets: inherit
