name: CI - Dev

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  # push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  test:
    uses: ./.github/workflows/test.yml
